# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [42]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [43]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([2,5,8])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([ [1,2,3], [4,5,6] ])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([ [ [1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9] ],
                [ [10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]] ])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [44]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [45]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [46]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [47]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [48]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [50]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.arange(0,100,3)
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [51]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a5 = np.random.randint(0,10, size=(7,2))
a5

array([[9, 1],
       [9, 3],
       [7, 6],
       [8, 7],
       [4, 1],
       [4, 7],
       [9, 8]], dtype=int32)

In [52]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random = np.random.rand(3, 5)
random

array([[0.28093451, 0.54269608, 0.14092422, 0.80219698, 0.07455064],
       [0.98688694, 0.77224477, 0.19871568, 0.00552212, 0.81546143],
       [0.70685734, 0.72900717, 0.77127035, 0.07404465, 0.35846573]])

In [53]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random2 = np.random.randint(0,10, size=(4,6))
random2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [54]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random3 = np.random.randint(1,10, size=(3,7))

# Find the unique numbers in the array you just created
random3, np.unique(random3)

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]], dtype=int32),
 array([1, 2, 3, 4, 5, 7, 9], dtype=int32))

In [55]:
# Find the 0'th index of the latest array you created
random3[0]

array([9, 1, 3, 7, 4, 9, 3], dtype=int32)

In [56]:
# Get the first 2 rows of latest array you created
random3[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [57]:
# Get the first 2 values of the first 2 rows of the latest array
random3[:2, :2]

array([[9, 1],
       [5, 3]], dtype=int32)

In [58]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random4 = np.random.randint(0,10, size=(3,5))
ones2 = np.ones((3,5))
random4

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]], dtype=int32)

In [59]:
# Add the two arrays together
sum1 = random4 + ones2
sum1

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [60]:
# Create another array of ones of shape (5, 3)
ones3 = np.ones((5,3))
ones3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
# Try add the array of ones and the other most recent array together


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [62]:
# Create another array of ones of shape (3, 5)
ones4 = np.ones((3,5))
ones4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [63]:
# Subtract the new array of ones from the other most recent array
subtract = ones4 - sum1
subtract

array([[-6., -7., -2.,  0., -3.],
       [-1., -7., -3., -1., -5.],
       [-5., -9., -3., -5., -1.]])

In [64]:
# Multiply the ones array with the latest array
mult = ones4 * subtract
mult

array([[-6., -7., -2.,  0., -3.],
       [-1., -7., -3., -1., -5.],
       [-5., -9., -3., -5., -1.]])

In [65]:
# Take the latest array to the power of 2 using '**'
square = mult ** 2
square

array([[36., 49.,  4.,  0.,  9.],
       [ 1., 49.,  9.,  1., 25.],
       [25., 81.,  9., 25.,  1.]])

In [66]:
# Do the same thing with np.square()
np.square(mult)

array([[36., 49.,  4.,  0.,  9.],
       [ 1., 49.,  9.,  1., 25.],
       [25., 81.,  9., 25.,  1.]])

In [67]:
# Find the mean of the latest array using np.mean()
np.mean(square)

np.float64(21.6)

In [68]:
# Find the maximum of the latest array using np.max()
np.max(square)

np.float64(81.0)

In [69]:
# Find the minimum of the latest array using np.min()
np.min(square)

np.float64(0.0)

In [70]:
# Find the standard deviation of the latest array
np.std(square)

np.float64(22.8)

In [71]:
# Find the variance of the latest array
np.var(square)

np.float64(519.84)

In [72]:
# Reshape the latest array to (3, 5, 1)
reshaped = np.reshape(square, shape=(3,5,1))
reshaped

array([[[36.],
        [49.],
        [ 4.],
        [ 0.],
        [ 9.]],

       [[ 1.],
        [49.],
        [ 9.],
        [ 1.],
        [25.]],

       [[25.],
        [81.],
        [ 9.],
        [25.],
        [ 1.]]])

In [73]:
# Transpose the latest array
reshaped.T

array([[[36.,  1., 25.],
        [49., 49., 81.],
        [ 4.,  9.,  9.],
        [ 0.,  1., 25.],
        [ 9., 25.,  1.]]])

What does the transpose do?

In [74]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand1 = np.random.randint(0,10, size=(3,3))
rand2 = np.random.randint(0,10, size=(3,2))

In [75]:
# Perform a dot product on the two newest arrays you created
np.dot(rand1,rand2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]], dtype=int32)

In [76]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand3 = np.random.randint(0,10, size=(4,3))
rand4 = np.random.randint(0,10, size=(4,3))

In [77]:
# Perform a dot product on the two newest arrays you created
np.dot(rand3,rand4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]], dtype=int32)

It doesn't work. How would you fix it?

In [78]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(rand3,rand4.T)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [79]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand5 = np.random.randint(0,10, size=(3,4))
rand6 = np.random.randint(0,10, size=(3,4))

In [80]:
rand5,rand6

(array([[6, 6, 7, 4],
        [2, 7, 5, 2],
        [0, 2, 4, 2]], dtype=int32),
 array([[0, 4, 9, 6],
        [6, 8, 9, 9],
        [2, 6, 0, 3]], dtype=int32))

In [81]:
# Compare the two arrays with '>'
rand5 > rand6

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

What happens when you compare the arrays with `>`?

In [82]:
# Compare the two arrays with '>='
rand5 >= rand6

array([[ True,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [83]:
# Find which elements of the first array are greater than 7
rand5 > 7

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [84]:
# Which parts of each array are equal? (try using '==')
rand5 == rand6

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [85]:
# Sort one of the arrays you just created in ascending order
np.sort(rand5)

array([[4, 6, 6, 7],
       [2, 2, 5, 7],
       [0, 2, 2, 4]], dtype=int32)

In [86]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand5)

array([[3, 0, 1, 2],
       [0, 3, 2, 1],
       [0, 1, 3, 2]])

In [87]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand5)

np.int64(2)

In [88]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand5)

np.int64(8)

In [89]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand5, axis=1)

array([2, 1, 2])

In [90]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rand5, axis=0)

array([2, 2, 2, 1])

In [91]:
# Create an array of normally distributed random numbers
arr_r = np.arange(0,10)
arr_r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arr_even = np.arange(1,101,2)
arr_even

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.